project:
  type: website

website:
  title: "Best Practices for Communicating PoS to Non-Statisticians in Drug Development"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left